# Generated by Django 5.1.3 on 2024-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='space_images/')),
                ('seating_map', models.ImageField(blank=True, null=True, upload_to='space_maps/')),
            ],
        ),
    ]
