# Generated by Django 5.1.3 on 2024-11-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='coworking_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.coworkingspace'),
            preserve_default=False,
        ),
    ]
