# Generated by Django 5.1.3 on 2024-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_space_coworking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='seating_map',
            field=models.ImageField(blank=True, null=True, upload_to='seating_maps/'),
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
