# Generated by Django 5.1.3 on 2024-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_coworkingspace_seating_map_delete_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworkingspace',
            name='seating_map',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='x',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='y',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
